#ifdef _WIN32
    #include <winsock2.h>
    #include <ws2tcpip.h>
    #include <windows.h>
    #define sleepMs(ms) Sleep(ms)
#else
    #include <unistd.h>
    #include <arpa/inet.h>
    #include <sys/socket.h>
    #define sleepMs(ms) usleep((ms) * 1000)
#endif
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>
#include <unistd.h>
#include <curses.h>
#include "../common/datastructures/arrayList.h"
#include "../common/datastructures/stringBuilder.h"

// this snippet generated by claude for cross-platform sleeping

// ^ end snippet generated by claude :p

//!!! MUST MATCH SERVER main.c !!!
#define PORT 6767
#define BUFFER_SIZE 1024
typedef enum {
    PKT_SET_NAME = 1,
    PKT_JOIN,
    PKT_LEAVE,
    PKT_CHAT,
    PKT_LIST
} PacketType;

typedef struct PacketHeader {
    unsigned char type;
    unsigned short length;
} PacketHeader;
// -- END STUFF FROM SERVER --

typedef enum {
    CONNECTION_OK,
    CONNECTION_FAILED,
} ConnectionStatusType;
typedef enum {
    UNSET_OK,
    UNSET_TOO_SHORT,
    UNSET_TOO_LONG,
    UNSET_INVALID,
    UNSET_TAKEN,
    UNSET_FAILED,
} UsernameSetResponseType;

typedef enum {
    CJOIN_OK,
    CJOIN_TOO_SHORT,
    CJOIN_TOO_LONG,
    CJOIN_INVALID,
    CJOIN_FAILED,
} ChannelJoinResponseType;

char* serverAddress = "167.71.176.13";
const int MAX_USERNAME_LENGTH = 16;
const int MIN_USERNAME_LENGTH = 3;
const int MIN_CHANNEL_LENGTH = 3;
const int MAX_CHANNEL_LENGTH = 16;
bool characterAllowedInUsername(char testChar) {
    return (
        (testChar == '_') ||
        (testChar >= '0' && testChar <= '9') ||
        (testChar >= 'A' && testChar <= 'Z') ||
        (testChar >= 'a' && testChar <= 'z')
    );
    // We only allow Roman letters, numbers, and underscores.
}

#ifdef _WIN32
    SOCKET sock = INVALID_SOCKET;
#else
    int sock = -1; //i changed the name cuz connId is annoying to type and sock is funnier cuz its a sock
#endif
bool connected = false;
char *username = NULL;
char *activeChannel = NULL;
char *reserveChannel = NULL;
ArrayList *messageCache;
StringBuilder *messageBuilder;

int getSock() {
    return sock;
}
char *getUsername() {
    if (username == NULL) return "";
    return username;
}
char *getActiveChannel() {
    if (activeChannel == NULL) return "";
    return activeChannel;
}

//helper functions to send stuff to server
int send_all(int fd, void *buf, int len){
    int total = 0;
    while (total < len) {
        int n = send(fd, (char*)buf + total, len - total, 0);
        if (n <= 0) return n;
        total += n;
    }
    return total;
}
void send_packet(PacketType type, char *data){
    PacketHeader header;
    header.type = (unsigned char) type;
    header.length = data ? strlen(data) : 0; //support for no data for some packets lol
    
    send_all(sock, &header, sizeof(header));

    if (header.length > 0) {
        send_all(sock, data, header.length);
    }
}

ConnectionStatusType connectToServer(){
    messageCache = newArrayListWithCapacity(sizeof(char *), getmaxy(curscr));
    messageCache->freeOnRemove = true;
    messageBuilder = newStringBuilder();
    // windows networking code learned on claude
    #ifdef _WIN32
        WSADATA wsa;
        if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) {
            return CONNECTION_FAILED;
        }
    #endif

    sock = socket(AF_INET, SOCK_STREAM, 0); //code to connect to server lol
    if (sock < 0){
        return CONNECTION_FAILED;
    }

    struct sockaddr_in server_addr; //simialr stuff as the server here
    server_addr.sin_family = AF_INET;
    server_addr.sin_port = htons(PORT); //make sure server port matches client port lol (6767)
    inet_pton(AF_INET, serverAddress, &server_addr.sin_addr); //assuming a local connection atm

    if (connect(sock, (struct sockaddr*)&server_addr, sizeof(server_addr)) < 0) {
        close(sock); //there's a problem if connect returns negative
        return CONNECTION_FAILED;
    }
    connected = true;
    return CONNECTION_OK;
}

void disconnectFromServer() {
    #ifdef _WIN32
        closesocket(sock);
        WSACleanup();
    #else
        close(sock);
    #endif
    connected = false;
}

UsernameSetResponseType trySetUsername(char *newUname) {
    // sanitize
    int len = strnlen(newUname, MAX_USERNAME_LENGTH+1);
    //                                             ^ +1 so we can tell the difference
    //                                             between > 16 and 16
    if (len < MIN_USERNAME_LENGTH) {
        return UNSET_TOO_SHORT;
    }
    if (len > MAX_USERNAME_LENGTH) {
        return UNSET_TOO_LONG;
    }
    for (int i = 0; i < len; i++) {
        char this = newUname[i];
        if (!characterAllowedInUsername(this)) {
            return UNSET_INVALID;
        }
    }
    if (len > MAX_USERNAME_LENGTH) {
        return UNSET_TOO_LONG;
    }

    send_packet(PKT_SET_NAME, newUname);
    free(username);
    username = strdup(newUname);
    return UNSET_OK;
}
ChannelJoinResponseType tryJoinChannel(char *channelName) {
    // sanitize
    int len = strnlen(channelName, MAX_CHANNEL_LENGTH+1);
    //                                             ^ +1 so we can tell the difference
    //                                             between > 16 and 16
    if (len < MIN_CHANNEL_LENGTH) {
        return CJOIN_TOO_SHORT;
    }
    if (len > MAX_CHANNEL_LENGTH) {
        return CJOIN_TOO_LONG;
    }
    for (int i = 0; i < len; i++) {
        char this = channelName[i];
        if (!characterAllowedInUsername(this)) {
            return CJOIN_INVALID;
        }
    }
    send_packet(PKT_JOIN, channelName);
    free(activeChannel);
    activeChannel = strdup(channelName);
    if (channelName != reserveChannel) {
        reserveChannel = strdup(channelName);
        alResizeList(messageCache, 0);
    }
    return CJOIN_OK;
}

//sample functions to send stuff for leaving channel & sending chat message:
void leaveChannel() {
    send_packet(PKT_LEAVE, NULL);
    free(activeChannel);
    activeChannel = NULL;
}

void sendChatMessage(char *msg) {
    send_packet(PKT_CHAT, msg);
}



void receivePartialMessage() {
    char buf[BUFFER_SIZE];
    int nRead = recv(sock, buf, BUFFER_SIZE, 0);
    if (nRead == 0) {
        endwin();
        #ifdef _WIN32
            WSACleanup();
        #endif
        printf("Connection closed. Process exited.");
        exit(0);
    } else if (nRead < 0) return;

    int nLeft = nRead;
    while (nLeft > 0) {
        int msgLen = strnlen(buf, nLeft); 
        sbAppend(messageBuilder, buf, msgLen);
        if (msgLen < nLeft) {
            // segment is end of message
            char *duped = strdup(messageBuilder->data);
            alAppend(messageCache, &duped);
            sbClear(messageBuilder);
            nLeft -= msgLen+1;
            memmove(buf, buf+msgLen+1, nLeft);
        } else {
            // segment is partial packet
            break;
        }
    }
}