#include <string.h>
#include <stdbool.h>
#include <stdlib.h>

// this snippet generated by claude for cross-platform sleeping
#ifdef _WIN32
    #include <windows.h>
    #define sleepMs(ms) Sleep(ms)
#else
    #include <unistd.h>
    #define sleepMs(ms) usleep((ms) * 1000)
#endif

typedef enum {
    CONNECTION_OK,
    CONNECTION_FAILED,
} ConnectionStatusType;
typedef enum {
    UNSET_OK,
    UNSET_TOO_SHORT,
    UNSET_TOO_LONG,
    UNSET_INVALID,
    UNSET_TAKEN,
    UNSET_FAILED,
} UsernameSetResponseType;

typedef enum {
    CJOIN_OK,
    CJOIN_TOO_SHORT,
    CJOIN_TOO_LONG,
    CJOIN_INVALID,
    CJOIN_FAILED,
} ChannelJoinResponseType;

const int MAX_USERNAME_LENGTH = 16;
const int MIN_USERNAME_LENGTH = 3;
const int MIN_CHANNEL_LENGTH = 3;
const int MAX_CHANNEL_LENGTH = 16;
bool characterAllowedInUsername(char testChar) {
    return (
        (testChar == '_') ||
        (testChar >= '0' && testChar <= '9') ||
        (testChar >= 'A' && testChar <= 'Z') ||
        (testChar >= 'a' && testChar <= 'z')
    );
    // We only allow Roman letters, numbers, and underscores.
}

int connId = 0;
char *username = NULL;
char *activeChannel = NULL;

int getConnId() {
    return connId;
}
char *getUsername() {
    if (username == NULL) return "";
    return username;
}
char *getActiveChannel() {
    if (activeChannel == NULL) return "";
    return activeChannel;
}

ConnectionStatusType connectToServer() {
    connId = 5; // dummy test implementation
    sleepMs(250);
    return CONNECTION_OK;
}
UsernameSetResponseType trySetUsername(char *newUname) {
    
    // sanitize
    int len = strnlen(newUname, MAX_USERNAME_LENGTH+1);
    //                                             ^ +1 so we can tell the difference
    //                                             between > 16 and 16
    if (len < MIN_USERNAME_LENGTH) {
        return UNSET_TOO_SHORT;
    }
    if (len > MAX_USERNAME_LENGTH) {
        return UNSET_TOO_LONG;
    }
    for (int i = 0; i < len; i++) {
        char this = newUname[i];
        if (!characterAllowedInUsername(this)) {
            return UNSET_INVALID;
        }
    }
    if (len > MAX_USERNAME_LENGTH) {
        return UNSET_TOO_LONG;
    }

    sleepMs(250); // simulate server connection
    free(username);
    username = strdup(newUname);
    return UNSET_OK;

}
ChannelJoinResponseType tryJoinChannel(char *channelName) {
    
    // sanitize
    int len = strnlen(channelName, MAX_USERNAME_LENGTH+1);
    //                                             ^ +1 so we can tell the difference
    //                                             between > 16 and 16
    if (len < MIN_CHANNEL_LENGTH) {
        return CJOIN_TOO_SHORT;
    }
    if (len > MAX_CHANNEL_LENGTH) {
        return CJOIN_TOO_LONG;
    }
    for (int i = 0; i < len; i++) {
        char this = channelName[i];
        if (!characterAllowedInUsername(this)) {
            return CJOIN_INVALID;
        }
    }
    sleepMs(250); // simulate server connection
    free(activeChannel);
    activeChannel = strdup(channelName);
    return CJOIN_OK;

}