#include "../component.h"
#include "../components/group.h"
#include "../components/text.h"
#include "../components/lineEdit.h"
#include "../../comms.h"
#include "../../interface.h"
#include "chooseChannel.h"
#include "chatScene.h"
#include <curses.h>
#include <stdbool.h>

// this snippet generated by claude for cross-platform sleeping
#ifdef _WIN32
    #include <windows.h>
    #define sleepMs(ms) Sleep(ms)
#else
    #include <unistd.h>
    #define sleepMs(ms) usleep((ms) * 1000)
#endif

// ui components
Group *chooseUsernameScene;
TextComponent *statusText;
LineEditComponent *textInput;

void chooseUsernameReceiveInput(Component *component, int c) {
    switch (c) {

        case '\r':
        case '\n':
            statusText->instructions = stringToInstructions("Setting Username...");
            rerender();
            UsernameSetResponseType status = trySetUsername(textInput->value->data);
            switch (status) {
                case UNSET_TOO_LONG:
                    statusText->instructions = stringToInstructions("Username too long.");
                    return;
                case UNSET_TOO_SHORT:
                    statusText->instructions = stringToInstructions("Username too short.");
                    return;
                case UNSET_INVALID:
                    statusText->instructions = stringToInstructions("Username contains invalid characters.");
                    return;
                case UNSET_TAKEN:
                    statusText->instructions = stringToInstructions("Username taken. Please try another!");
                    return;
                case UNSET_FAILED:
                    statusText->instructions = stringToInstructions("Username set failed. Please try again.");
                    return;
                case UNSET_OK:
                    statusText->instructions = stringToInstructions("Set successfully!");
                    rerender();
                    sleepMs(500);
                    if (reserveChannel == NULL) {
                        screenComponent = (Component*) chooseChannelScene;
                    } else {
                        tryJoinChannel(reserveChannel);
                        screenComponent = (Component*) chatScene;
                    }
                    return;
            }
            break;
        default:
            textInput->component.receiveInput((Component *) textInput, c);
            break;
    }
}

void initializeChooseUsername() {
    // set up ui components necessary for the choose username scene

    chooseUsernameScene = newGroup();
    chooseUsernameScene->component.receiveInput = chooseUsernameReceiveInput;
    chooseUsernameScene->component.anchor.size.xType = VEC_RELATIVE;
    chooseUsernameScene->component.anchor.size.yType = VEC_RELATIVE;
    chooseUsernameScene->component.anchor.size.relX = 1;
    chooseUsernameScene->component.anchor.size.relY = 1;
    statusText = newTextComponent();
    statusText->component.anchor.origin.relX = 0.5;
    statusText->component.anchor.origin.relY = 0.5;
    statusText->direction = TRD_MIDDLE_MIDDLE;
    statusText->component.anchor.size.xType = VEC_RELATIVE;
    statusText->component.anchor.size.relX = 1.0;
    statusText->component.anchor.size.absY = 3;
    statusText->component.anchor.position.xType = VEC_RELATIVE;
    statusText->component.anchor.position.yType = VEC_RELATIVE;
    statusText->component.anchor.position.relX = 0.5;
    statusText->component.anchor.position.relY = 0.4;
    alAppend(chooseUsernameScene->components, &statusText);
    statusText->instructions = stringToInstructions("Enter a username <= 16 characters (A-z, 0-9, \\_). Press ENTER to continue.");
    textInput = newLineEdit();
    textInput->component.anchor.size.absX = 26;
    textInput->component.anchor.size.absY = 1;
    textInput->component.anchor.origin.relX = 0.5;
    textInput->component.anchor.origin.relY = 0.5;
    textInput->component.anchor.position.xType = VEC_RELATIVE;
    textInput->component.anchor.position.yType = VEC_RELATIVE;
    textInput->component.anchor.position.relX = 0.5;
    textInput->component.anchor.position.relY = 0.5;
    textInput->label = "Username: ";
    textInput->active = true;
    alAppend(chooseUsernameScene->components, &textInput);

}

void resetChooseUsername() {
    // clears the text input for changing the username
    statusText->instructions = stringToInstructions("Enter a username <= 16 characters (A-z, 0-9, \\_). Press ENTER to continue.");
    sbClear(textInput->value);
    textInput->cursor = 0;
}