#include "../component.h"
#include "../components/group.h"
#include "../components/text.h"
#include "../components/lineEdit.h"
#include "../../comms.h"
#include "../../interface.h"
#include "chatScene.h"
#include <curses.h>
#include <stdbool.h>

// this snippet generated by claude for cross-platform sleeping
#ifdef _WIN32
    #include <windows.h>
    #define sleepMs(ms) Sleep(ms)
#else
    #include <unistd.h>
    #define sleepMs(ms) usleep((ms) * 1000)
#endif


Group *chooseChannelScene;
TextComponent *ccStatusText;
LineEditComponent *ccTextInput;

void chooseChannelReceiveInput(Component *component, int c) {
    switch (c) {

        case '\r':
        case '\n':
            ccStatusText->instructions = stringToInstructions("Joining Channel...");
            rerender();
            ChannelJoinResponseType status = tryJoinChannel(ccTextInput->value->data);
            switch (status) {
                case CJOIN_TOO_LONG:
                    ccStatusText->instructions = stringToInstructions("Channel name too long.");
                    return;
                case CJOIN_TOO_SHORT:
                    ccStatusText->instructions = stringToInstructions("Channel name too short.");
                    return;
                case CJOIN_INVALID:
                    ccStatusText->instructions = stringToInstructions("Channel name contains invalid characters.");
                    return;
                case CJOIN_FAILED:
                    ccStatusText->instructions = stringToInstructions("Joining channel failed. Please try again.");
                    return;
                case CJOIN_OK:
                    ccStatusText->instructions = stringToInstructions("Joined successfully!");
                    rerender();
                    sleepMs(500);
                    updateChatHeader();
                    screenComponent = (Component*) chatScene;
                    return;
            }
            break;
        default:
            ccTextInput->component.receiveInput((Component *) ccTextInput, c);
            break;
    }
}

void initializeChooseChannel() {
    chooseChannelScene = newGroup();
    chooseChannelScene->component.receiveInput = chooseChannelReceiveInput;
    chooseChannelScene->component.anchor.size.xType = VEC_RELATIVE;
    chooseChannelScene->component.anchor.size.yType = VEC_RELATIVE;
    chooseChannelScene->component.anchor.size.relX = 1;
    chooseChannelScene->component.anchor.size.relY = 1;
    ccStatusText = newTextComponent();
    ccStatusText->component.anchor.origin.relX = 0.5;
    ccStatusText->component.anchor.origin.relY = 0.5;
    ccStatusText->direction = TRD_MIDDLE_MIDDLE;
    ccStatusText->component.anchor.size.xType = VEC_RELATIVE;
    ccStatusText->component.anchor.size.relX = 1.0;
    ccStatusText->component.anchor.size.absY = 3;
    ccStatusText->component.anchor.position.xType = VEC_RELATIVE;
    ccStatusText->component.anchor.position.yType = VEC_RELATIVE;
    ccStatusText->component.anchor.position.relX = 0.5;
    ccStatusText->component.anchor.position.relY = 0.4;
    alAppend(chooseChannelScene->components, &ccStatusText);
    ccStatusText->instructions = stringToInstructions("Enter a channel <= 16 characters (A-z, 0-9, \\_). Press ENTER to continue.");
    ccTextInput = newLineEdit();
    ccTextInput->component.anchor.size.absX = 26;
    ccTextInput->component.anchor.size.absY = 1;
    ccTextInput->component.anchor.origin.relX = 0.5;
    ccTextInput->component.anchor.origin.relY = 0.5;
    ccTextInput->component.anchor.position.xType = VEC_RELATIVE;
    ccTextInput->component.anchor.position.yType = VEC_RELATIVE;
    ccTextInput->component.anchor.position.relX = 0.5;
    ccTextInput->component.anchor.position.relY = 0.5;
    ccTextInput->label = "Channel: ";
    ccTextInput->active = true;
    alAppend(chooseChannelScene->components, &ccTextInput);

}

void resetChooseChannel() {
    ccStatusText->instructions = stringToInstructions("Enter a channel <= 16 characters (A-z, 0-9, \\_). Press ENTER to continue.");
    sbClear(ccTextInput->value);
    ccTextInput->cursor = 0;
}