#include "../component.h"
#include "../components/group.h"
#include "../components/text.h"
#include "../../comms.h"
#include "../../interface.h"
#include "chooseUsername.h"
#include <curses.h>

// this snippet generated by claude for cross-platform sleeping
#ifdef _WIN32
    #include <windows.h>
    #define sleepMs(ms) Sleep(ms)
#else
    #include <unistd.h>
    #define sleepMs(ms) usleep((ms) * 1000)
#endif


Group *connectScene;
TextComponent *text;

void connectSceneReceiveInput(Component *component, int c) {
    switch (c) {
        case ' ':
            text->instructions = stringToInstructions("Connecting...");
            rerender();
            ConnectionStatusType status = connectToServer();
            switch (status) {
                case CONNECTION_FAILED:
                    text->instructions = stringToInstructions("Connection failed. Press SPACE to try again...");
                    return;
                case CONNECTION_OK:
                    text->instructions = stringToInstructions("Connected successfully!");
                    rerender();
                    sleepMs(500);
                    screenComponent = (Component*) chooseUsernameScene;
                    return;
                
            }
            break;
    }
}

void initializeConnectScene() {
    connectScene = newGroup();
    text = newTextComponent();
    connectScene->component.receiveInput = connectSceneReceiveInput;
    connectScene->component.anchor.size.xType = VEC_RELATIVE;
    connectScene->component.anchor.size.yType = VEC_RELATIVE;
    connectScene->component.anchor.size.relX = 1;
    connectScene->component.anchor.size.relY = 1;
    text->component.anchor.origin.relX = 0.5;
    text->component.anchor.origin.relY = 0.5;
    text->direction = TRD_MIDDLE_MIDDLE;
    text->component.anchor.size.xType = VEC_RELATIVE;
    text->component.anchor.size.relX = 1.0;
    text->component.anchor.size.absY = 3;
    text->component.anchor.position.xType = VEC_RELATIVE;
    text->component.anchor.position.yType = VEC_RELATIVE;
    text->component.anchor.position.relX = 0.5;
    text->component.anchor.position.relY = 0.5;
    alAppend(connectScene->components, &text);
    text->instructions = stringToInstructions("Press SPACE to connect...");
}