#include "../component.h"
#include "../components/group.h"
#include "../components/text.h"
#include "../components/lineEdit.h"
#include "../../comms.h"
#include "../../interface.h"
#include "chatScene.h"
#include "chooseUsername.h"
#include "chooseChannel.h"
#include <curses.h>
#include <stdbool.h>

// this snippet generated by claude for cross-platform sleeping
#ifdef _WIN32
    #include <windows.h>
    #define sleepMs(ms) Sleep(ms)
#else
    #include <unistd.h>
    #define sleepMs(ms) usleep((ms) * 1000)
#endif

// ui components
Group *optionsScene;
TextComponent *opt_returnText;
TextComponent *opt_changeChannelText;
TextComponent *opt_changeUsernameText;
TextComponent *opt_exitText;

void optionsReceiveInput(Component *component, int c) {
    switch (c) {
        case 27: // escape
            screenComponent = (Component *) chatScene;
            break; 
        case 'e':
            cleanup();
            disconnectFromServer();
            exit(0);
        case 'u':
            resetChooseUsername();
            leaveChannel();
            screenComponent = (Component *) chooseUsernameScene;
            break; 
        case 'c':
            leaveChannel();
            free(reserveChannel);
            reserveChannel = NULL;
            resetChooseChannel();
            screenComponent = (Component *) chooseChannelScene;    
            break;
    }
}

void initializeOptionsScene() {
    // set up ui components necessary for the options scene

    optionsScene = newGroup();
    optionsScene->component.receiveInput = optionsReceiveInput;
    optionsScene->component.anchor.size.xType = VEC_RELATIVE;
    optionsScene->component.anchor.size.yType = VEC_RELATIVE;
    optionsScene->component.anchor.size.relX = 1;
    optionsScene->component.anchor.size.relY = 1;
    optionsScene->yPad = 1;
    optionsScene->constraint = GROUP_VBOX;
    
    opt_returnText = newTextComponent();
    opt_returnText->component.anchor.origin.relX = 0.5;
    opt_returnText->component.anchor.origin.relY = 0;
    opt_returnText->direction = TRD_MIDDLE_MIDDLE;
    opt_returnText->component.anchor.size.absX = 30;
    opt_returnText->component.anchor.size.absY = 3;
    opt_returnText->component.anchor.position.xType = VEC_RELATIVE;
    opt_returnText->component.anchor.position.relX = 0.5;
    opt_returnText->component.anchor.position.absY = 0;
    alConcatAndFree(opt_returnText->instructions, stringToInstructions("Press ESC to Go Back"));
    
    opt_changeChannelText = newTextComponent();
    opt_changeChannelText->component.anchor.origin.relX = 0.5;
    opt_changeChannelText->component.anchor.origin.relY = 0;
    opt_changeChannelText->direction = TRD_MIDDLE_MIDDLE;
    opt_changeChannelText->component.anchor.size.absX = 30;
    opt_changeChannelText->component.anchor.size.absY = 3;
    opt_changeChannelText->component.anchor.position.xType = VEC_RELATIVE;
    opt_changeChannelText->component.anchor.position.relX = 0.5;
    opt_changeChannelText->component.anchor.position.absY = 0;
    alConcatAndFree(opt_changeChannelText->instructions, stringToInstructions("Press C to Change Channel"));
    
    opt_changeUsernameText = newTextComponent();
    opt_changeUsernameText->component.anchor.origin.relX = 0.5;
    opt_changeUsernameText->component.anchor.origin.relY = 0;
    opt_changeUsernameText->direction = TRD_MIDDLE_MIDDLE;
    opt_changeUsernameText->component.anchor.size.absX = 30;
    opt_changeUsernameText->component.anchor.size.absY = 3;
    opt_changeUsernameText->component.anchor.position.xType = VEC_RELATIVE;
    opt_changeUsernameText->component.anchor.position.relX = 0.5;
    opt_changeUsernameText->component.anchor.position.absY = 0;
    alConcatAndFree(opt_changeUsernameText->instructions, stringToInstructions("Press U to Change Username"));
    
    opt_exitText = newTextComponent();
    opt_exitText->component.anchor.origin.relX = 0.5;
    opt_exitText->component.anchor.origin.relY = 0;
    opt_exitText->direction = TRD_MIDDLE_MIDDLE;
    opt_exitText->component.anchor.size.absX = 30;
    opt_exitText->component.anchor.size.absY = 3;
    opt_exitText->component.anchor.position.xType = VEC_RELATIVE;
    opt_exitText->component.anchor.position.relX = 0.5;
    opt_exitText->component.anchor.position.absY = 0;
    alConcatAndFree(opt_exitText->instructions, stringToInstructions("Press E to Exit"));

    alAppend(optionsScene->components, &opt_returnText);
    alAppend(optionsScene->components, &opt_changeChannelText);
    alAppend(optionsScene->components, &opt_changeUsernameText);
    alAppend(optionsScene->components, &opt_exitText);

}